import { TextStyle, StyleProp } from "react-native";
import { TextProps } from "@/components/Text";
import { TxKeyPath } from "@/i18n";
type DropdownProps<T> = {
    queryKey: string;
    fetcher: () => Promise<T[] | undefined>;
    value?: string | number;
    onChange?: (item: T) => void;
    keyExtractor: (item: T) => string;
    labelExtractor: (item: T) => string;
    labelTx?: TxKeyPath;
    style?: StyleProp<TextStyle>;
    disabled?: boolean;
    filter?: (items: T[] | undefined) => T[];
    helperTx?: TxKeyPath;
    helper?: string;
    HelperTextProps?: TextProps;
    status?: "error" | "disabled";
    helperTxOptions?: TextProps["txOptions"];
};
export declare function Dropdown<T>({ queryKey, fetcher, value, onChange, keyExtractor, labelExtractor, labelTx, style, disabled, filter, HelperTextProps, status, helper, helperTx, helperTxOptions, }: DropdownProps<T>): import("react").JSX.Element;
export {};
